const PEOPLE=['Tessa','Tammo','Isa','Henny','Jasper','Marijne','Joris','Billie','Pien','Louis','Marit','Max','Stan','Simon','Zemen','Roos','Lize','Thijs','Lisanne','Anna','Egor','Zoë','Lucas','Koen','Vincent'];
const ADMIN_USERS=['Thijs','Billie','Henny'];
const PRODUCTS={beer:{name:'Pils',emoji:'🍺',color:'#e5b84f',unit:'flesjes'},soda:{name:'Fris',emoji:'🥤',color:'#e46f3d',unit:'blikjes'},snack:{name:'Tjaps',emoji:'🍫',color:'#75567d',unit:'stuks'}};
const SUPABASE_URL='https://fvlfejqfilynvlahzvni.supabase.co';
const SUPABASE_KEY='sb_publishable_Oav_kx2DbFi7ponzds0K-A_UelwBbkf';
const HOUSE_CODE_KEY='de-turf-house-code';
const ADMIN_TOKEN_KEY='de-turf-admin-token',ADMIN_NAME_KEY='de-turf-admin-name';
const STORE_KEY='de-turf-v2';
const freshState=()=>({user:null,stock:{beer:96,soda:48,snack:35},history:[],periodStart:new Date(new Date().setHours(0,0,0,0)).getTime(),prices:{beer:100,soda:80,snack:70},credits:Object.fromEntries(PEOPLE.map(p=>[p,0])),adminPins:{}});
let state=JSON.parse(localStorage.getItem(STORE_KEY)||'null')||freshState();
state.prices={beer:100,soda:80,snack:70,...state.prices};state.credits={...freshState().credits,...state.credits};state.adminPins=state.adminPins||{};
if(!PEOPLE.includes(state.user))state.user=null;
let adminToken=localStorage.getItem(ADMIN_TOKEN_KEY)||'',savedAdminName=localStorage.getItem(ADMIN_NAME_KEY)||'';
if(ADMIN_USERS.includes(state.user)&&(!adminToken||savedAdminName!==state.user))state.user=null;
let roundProduct='beer',roundPeople=new Set(),adjustProduct='beer',adjustAmount=24,adjustDirection=1,creditPerson='Tessa',reportBlob=null,pendingAdmin=null,pinSetup=false,connected=false,houseCode=localStorage.getItem(HOUSE_CODE_KEY)||'';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const save=()=>localStorage.setItem(STORE_KEY,JSON.stringify(state));
const initials=n=>n.slice(0,2).toUpperCase();
const money=c=>new Intl.NumberFormat('nl-BE',{style:'currency',currency:'EUR'}).format(c/100);
const dateLabel=ts=>new Intl.DateTimeFormat('nl-BE',{day:'numeric',month:'short',year:'numeric'}).format(ts);
const periodHistory=()=>state.history.filter(x=>x.time>=state.periodStart&&PEOPLE.includes(x.person));
const spend=person=>periodHistory().filter(x=>x.person===person).reduce((n,x)=>n+state.prices[x.product],0);
const balance=person=>(state.credits[person]||0)-spend(person);
const countsFor=person=>Object.fromEntries(Object.keys(PRODUCTS).map(k=>[k,periodHistory().filter(x=>x.person===person&&x.product===k).length]));
const isAdmin=()=>ADMIN_USERS.includes(state.user)&&!!adminToken&&savedAdminName===state.user;
async function remoteCall(name,params={}){if(!houseCode)throw new Error('Huiscode ontbreekt');const response=await fetch(`${SUPABASE_URL}/rest/v1/rpc/${name.replace('turf_','turf_secure_')}`,{method:'POST',headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${SUPABASE_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({...params,p_house_code:houseCode})});if(!response.ok)throw new Error(await response.text());const text=await response.text();return text?JSON.parse(text):null}
async function syncRemote(silent=false){try{const remote=await remoteCall('turf_get_state'),user=state.user;state={...state,...remote,user,credits:{...freshState().credits,...remote.credits},adminPins:remote.adminPins||{}};connected=true;save();render();return true}catch(e){connected=false;if(!silent)showToast('Eerst het Supabase-installatiebestand uitvoeren');return false}}
function showToast(text){const t=$('#toast');t.textContent=text;t.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.classList.remove('show'),2200)}
function chooseProfile(name){state.user=name;save();$('#profileDialog').close();render();showToast(`Hoi ${name}, je bent klaar om te turven`)}
async function requestProfile(name){if(!ADMIN_USERS.includes(name)){chooseProfile(name);return}if(adminToken&&savedAdminName===name){try{if(await remoteCall('turf_admin_session_valid',{p_name:name,p_token:adminToken})){chooseProfile(name);return}}catch(e){}localStorage.removeItem(ADMIN_TOKEN_KEY);localStorage.removeItem(ADMIN_NAME_KEY);adminToken='';savedAdminName=''}pendingAdmin=name;pinSetup=!state.adminPins[name];$('#pinTitle').textContent=pinSetup?`PIN instellen voor ${name}`:`Welkom terug, ${name}`;$('#pinCopy').textContent=pinSetup?'Kies een persoonlijke PIN van vier cijfers.':'Voer je viercijferige beheer-PIN in.';$('#pinConfirmField').hidden=!pinSetup;$('#pinConfirm').required=pinSetup;$('#pinSubmit').textContent=pinSetup?'PIN instellen':'Ontgrendel beheer';$('#pinInput').value='';$('#pinConfirm').value='';$('#pinError').textContent='';$('#profileDialog').close();$('#pinDialog').showModal();setTimeout(()=>$('#pinInput').focus(),100)}
async function addTurf(product,person=state.user,quiet=false){if(!person){$('#profileDialog').showModal();return}try{await remoteCall('turf_add',{p_person:person,p_product:product});await syncRemote(true);if(!quiet)showToast(`${PRODUCTS[product].emoji} ${PRODUCTS[product].name} · saldo ${money(balance(person))}`)}catch(e){showToast('Turven mislukt — controleer de verbinding')}}
async function undoOne(person,product){try{await remoteCall('turf_undo',{p_person:person,p_product:product});await syncRemote(true);showToast('Laatste turfje ongedaan gemaakt')}catch(e){showToast('Ongedaan maken mislukt')}}
function grouped(items){const map=new Map();items.forEach(x=>{const key=`${x.person}|${x.product}`;const g=map.get(key)||{person:x.person,product:x.product,count:0,time:0};g.count++;g.time=Math.max(g.time,x.time);map.set(key,g)});return [...map.values()].sort((a,b)=>b.time-a.time)}
function renderProducts(){$('#productGrid').innerHTML=Object.entries(PRODUCTS).map(([key,p])=>`<button class="product-card" data-product="${key}"><span class="emoji">${p.emoji}</span><strong>${p.name}</strong><small>${money(state.prices[key])}</small><span class="plus">+</span></button>`).join('');$$('.product-card').forEach(b=>b.onclick=()=>{b.classList.add('flash');addTurf(b.dataset.product)})}
function totalsHtml(items,undoable=true){const groups=grouped(items);if(!groups.length)return '<div class="empty">Nog niets geturfd in deze periode.</div>';return groups.map(x=>`<div class="recent-item"><span class="mini-avatar">${initials(x.person)}</span><div><strong>${x.person}</strong><small>Sinds ${dateLabel(state.periodStart)} · ${money(x.count*state.prices[x.product])}</small></div><span class="item-emoji">${PRODUCTS[x.product].emoji}</span><span class="count-badge">×${x.count}</span>${undoable?`<button class="undo" data-person="${x.person}" data-product-undo="${x.product}" aria-label="Eén ongedaan maken">↶</button>`:''}</div>`).join('')}
function renderHistory(){const current=periodHistory();$('#recentList').innerHTML=state.user?totalsHtml(current.filter(x=>x.person===state.user)):totalsHtml([]);$('#historyList').innerHTML=totalsHtml(current,true);$$('[data-product-undo]').forEach(b=>b.onclick=()=>undoOne(b.dataset.person,b.dataset.productUndo))}
function renderBalance(){const card=$('#balanceCard');if(!state.user){card.className='balance-card empty';return}const b=balance(state.user);card.className=`balance-card ${b<0?'negative':''}`;card.innerHTML=`<div><span>Jouw krediet</span><strong>${money(b)}</strong></div><span>${b<0?'Je staat rood — vul binnenkort aan':'Beschikbaar na je turfjes'}</span>`}
function renderStock(){const max={beer:120,soda:72,snack:50};$('#stockCards').innerHTML=Object.entries(PRODUCTS).map(([key,p])=>{const pct=Math.min(100,state.stock[key]/max[key]*100),low=pct<25;return `<div class="stock-card"><div class="stock-top"><span class="emoji">${p.emoji}</span><div><strong>${p.name}</strong><small>${low?'Bijna op — tijd om te halen':'Voorraad ziet er goed uit'}</small></div><span class="stock-count">± ${state.stock[key]}</span></div><div class="bar"><i style="width:${pct}%;background:${low?'#d24d3c':p.color}"></i></div></div>`}).join('')}
function renderHouse(){const current=periodHistory(),counts=Object.fromEntries(PEOPLE.map(p=>[p,current.filter(x=>x.person===p).length])),beerCounts=Object.fromEntries(PEOPLE.map(p=>[p,current.filter(x=>x.person===p&&x.product==='beer').length])),active=Object.values(counts).filter(Boolean).length;$('#houseSummary').innerHTML=`<div class="summary-card"><strong>${current.length}</strong><small>turfjes sinds ${dateLabel(state.periodStart)}</small></div><div class="summary-card"><strong>${active}/25</strong><small>bewoners actief</small></div>`;$('#peopleList').innerHTML=[...PEOPLE].sort((a,b)=>beerCounts[b]-beerCounts[a]).map(p=>`<div class="person-row"><span class="mini-avatar">${initials(p)}</span><strong>${p}</strong><div class="person-meta"><span class="${balance(p)<0?'balance-negative':'balance-positive'}">${money(balance(p))}</span><small>🍺 ${beerCounts[p]} · ${counts[p]} totaal</small></div></div>`).join('')}
function renderPrices(){$('#priceSettings').innerHTML=Object.entries(PRODUCTS).map(([k,p])=>`<div class="price-field"><span>${p.emoji}</span><label>${p.name}<input data-price="${k}" type="number" min="0" step="0.05" value="${(state.prices[k]/100).toFixed(2)}" aria-label="Prijs ${p.name}"></label></div>`).join('');$$('[data-price]').forEach(i=>i.onchange=async()=>{if(!isAdmin())return;try{await remoteCall('turf_admin_price',{p_admin:state.user,p_pin:adminToken,p_product:i.dataset.price,p_cents:Math.max(0,Math.round(Number(i.value)*100))});await syncRemote(true);showToast('Prijs opgeslagen')}catch(e){showToast('Prijs wijzigen mislukt')}})}
function renderCredits(){$('#creditAdmin').innerHTML=PEOPLE.map(p=>`<div class="credit-row"><div><strong>${p}</strong><small>${money(state.credits[p])} gestort · ${money(spend(p))} verbruikt · <span class="${balance(p)<0?'balance-negative':'balance-positive'}">${money(balance(p))}</span></small></div><div class="credit-actions"><button class="add-credit" data-add-credit="${p}">+ krediet</button><button class="settle-credit" data-settle="${p}" ${balance(p)>=0?'disabled':''}>Vereffen</button></div></div>`).join('');$$('[data-add-credit]').forEach(b=>b.onclick=()=>openCredit(b.dataset.addCredit));$$('[data-settle]').forEach(b=>b.onclick=()=>settle(b.dataset.settle))}
function renderAdmin(){const current=periodHistory(),today=current.filter(x=>Date.now()-x.time<864e5).length,red=PEOPLE.filter(p=>balance(p)<0).length;$('#adminStats').innerHTML=`<div class="admin-stat"><strong>${today}</strong><small>vandaag</small></div><div class="admin-stat"><strong>${current.length}</strong><small>deze periode</small></div><div class="admin-stat"><strong>${red}</strong><small>in het rood</small></div>`;$('#financeAdmin').hidden=!isAdmin();$('#financeDenied').hidden=isAdmin();$('#periodLabel').textContent=`Sinds ${dateLabel(state.periodStart)}`;renderPrices();renderCredits();$('#adminStock').innerHTML=Object.entries(PRODUCTS).map(([key,p])=>`<div class="admin-stock-row"><span class="emoji">${p.emoji}</span><div><strong>${p.name}</strong><small>${state.stock[key]} ${p.unit}</small></div><button data-adjust="${key}">+ Vul aan</button></div>`).join('');$$('[data-adjust]').forEach(b=>b.onclick=()=>openAdjust(b.dataset.adjust))}
function render(){const hr=new Date().getHours();$('#greeting').textContent=hr<12?'GOEDEMORGEN':hr<18?'GOEDEMIDDAG':'GOEDENAVOND';$('#welcomeName').textContent=state.user?`Hoi, ${state.user}`:'Wie ben jij?';$('#profileButton').textContent=state.user?initials(state.user):'?';renderBalance();renderProducts();renderHistory();renderStock();renderHouse();renderAdmin()}
function openRound(){roundPeople=new Set(state.user?[state.user]:[]);roundProduct='beer';renderRound();$('#roundDialog').showModal()}
function renderRound(){$('#roundProducts').innerHTML=Object.entries(PRODUCTS).map(([k,p])=>`<button type="button" class="round-product ${k===roundProduct?'selected':''}" data-rproduct="${k}">${p.emoji} ${p.name}</button>`).join('');$('#roundNames').innerHTML=PEOPLE.map(p=>`<button type="button" class="round-name ${roundPeople.has(p)?'selected':''}" data-rperson="${p}">${p}</button>`).join('');const n=roundPeople.size;$('#confirmRound').disabled=!n;$('#confirmRound').textContent=n?`${n}× ${PRODUCTS[roundProduct].name} turven`:'Selecteer huisgenoten';$$('[data-rproduct]').forEach(b=>b.onclick=()=>{roundProduct=b.dataset.rproduct;renderRound()});$$('[data-rperson]').forEach(b=>b.onclick=()=>{roundPeople.has(b.dataset.rperson)?roundPeople.delete(b.dataset.rperson):roundPeople.add(b.dataset.rperson);renderRound()})}
function renderAdjustMode(){const adding=adjustDirection===1;$('#stockAddMode').classList.toggle('selected',adding);$('#stockRemoveMode').classList.toggle('selected',!adding);$('#adjustTitle').textContent=`${PRODUCTS[adjustProduct].name} ${adding?'aanvullen':'verminderen'}`;$('#adjustCopy').textContent=adding?'Hoeveel stuks wil je toevoegen?':'Hoeveel stuks moeten van de telling af?';$('#adjustSubmit').textContent=adding?'Toevoegen':'Van voorraad afhalen';$('#adjustSubmit').style.background=adding?'':'#a64132'}
function openAdjust(key){adjustProduct=key;adjustAmount=key==='snack'?10:24;adjustDirection=1;$('#adjustIcon').textContent=PRODUCTS[key].emoji;$('#adjustAmount').textContent=adjustAmount;renderAdjustMode();$('#adjustDialog').showModal()}
function openCredit(person){if(!isAdmin())return;creditPerson=person;$('#creditTitle').textContent=`Krediet voor ${person}`;$('#creditAmount').value='10.00';$('#creditDialog').showModal()}
async function settle(person){if(!isAdmin())return;try{await remoteCall('turf_admin_settle',{p_admin:state.user,p_pin:adminToken,p_person:person});await syncRemote(true);showToast(`${person} is vereffend`)}catch(e){showToast('Vereffenen mislukt')}}
function createReport(){if(!isAdmin())return;const rows=[...PEOPLE].sort((a,b)=>balance(a)-balance(b)),width=1080,rowHeight=62,height=300+rows.length*rowHeight+90,canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;const c=canvas.getContext('2d');c.fillStyle='#f5f0e7';c.fillRect(0,0,width,height);c.fillStyle='#1d4838';c.fillRect(0,0,width,220);c.fillStyle='#fffdf8';c.font='700 54px Arial';c.fillText('DE TURF',70,88);c.font='700 34px Arial';c.fillText('Eindafrekening',70,145);c.font='24px Arial';c.fillStyle='#cfe1d8';c.fillText(`${dateLabel(state.periodStart)} t/m ${dateLabel(Date.now())}`,70,188);c.fillStyle='#19241f';c.font='700 25px Arial';c.fillText('BEWONER',70,270);c.textAlign='right';c.fillText('GESTORT',700,270);c.fillText('VERBRUIKT',875,270);c.fillText('SALDO',1010,270);c.textAlign='left';rows.forEach((person,i)=>{const y=305+i*rowHeight;if(i%2===0){c.fillStyle='#fffdf8';c.fillRect(45,y-35,990,rowHeight)}c.fillStyle='#19241f';c.font='600 25px Arial';c.fillText(`${i+1}.  ${person}`,70,y+5);c.textAlign='right';c.font='24px Arial';c.fillStyle='#56615b';c.fillText(money(state.credits[person]),700,y+5);c.fillText(money(spend(person)),875,y+5);c.font='700 25px Arial';c.fillStyle=balance(person)<0?'#b74735':'#1d6b4d';c.fillText(money(balance(person)),1010,y+5);c.textAlign='left'});const total=PEOPLE.reduce((n,p)=>n+balance(p),0);c.fillStyle='#1d4838';c.fillRect(45,height-75,990,55);c.fillStyle='white';c.font='700 25px Arial';c.fillText('Totaalsaldo huis',70,height-40);c.textAlign='right';c.fillText(money(total),1010,height-40);canvas.toBlob(blob=>{reportBlob=blob;$('#reportImage').src=URL.createObjectURL(blob);$('#reportDialog').showModal()},'image/png')}
function reportFile(){return new File([reportBlob],`de-turf-afrekening-${new Date().toISOString().slice(0,10)}.png`,{type:'image/png'})}
function downloadReport(){if(!isAdmin()||!reportBlob)return;const a=document.createElement('a');a.href=URL.createObjectURL(reportBlob);a.download=reportFile().name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function reportText(){return [`De Turf · eindafrekening`,`Periode: ${dateLabel(state.periodStart)} t/m ${dateLabel(Date.now())}`,'',...[...PEOPLE].sort((a,b)=>balance(a)-balance(b)).map(p=>`${p}: ${money(balance(p))}`)].join('\n')}
async function copyReport(){if(!isAdmin()||!reportBlob)return;try{if(navigator.clipboard?.write&&window.ClipboardItem){await navigator.clipboard.write([new ClipboardItem({'image/png':reportBlob})]);showToast('Afbeelding gekopieerd — plak ze in WhatsApp');return}throw new Error('image clipboard unavailable')}catch(e){const area=document.createElement('textarea');area.value=reportText();area.style.position='fixed';area.style.opacity='0';document.body.appendChild(area);area.select();document.execCommand('copy');area.remove();showToast('Saldolijst als tekst gekopieerd')}}
$('#profileButton').onclick=()=>$('#profileDialog').showModal();
$('#nameGrid').innerHTML=PEOPLE.map(p=>`<button type="button" class="name-button" data-name="${p}">${p}${ADMIN_USERS.includes(p)?' 🔒':''}</button>`).join('');$$('[data-name]').forEach(b=>b.onclick=()=>requestProfile(b.dataset.name));
$('#roundButton').onclick=openRound;$('#selectAll').onclick=()=>{roundPeople=new Set(PEOPLE);renderRound()};$('#clearAll').onclick=()=>{roundPeople.clear();renderRound()};
$('#roundForm').onsubmit=async e=>{e.preventDefault();const people=[...roundPeople];try{await remoteCall('turf_add_round',{p_people:people,p_product:roundProduct});await syncRemote(true);$('#roundDialog').close();showToast(`${people.length}× ${PRODUCTS[roundProduct].name} succesvol geturfd`)}catch(err){showToast('Rondje turven mislukt')}};
$('#minusAdjust').onclick=()=>{adjustAmount=Math.max(1,adjustAmount-1);$('#adjustAmount').textContent=adjustAmount};$('#plusAdjust').onclick=()=>{adjustAmount++;$('#adjustAmount').textContent=adjustAmount};
$('#stockAddMode').onclick=()=>{adjustDirection=1;renderAdjustMode()};$('#stockRemoveMode').onclick=()=>{adjustDirection=-1;renderAdjustMode()};
$('#adjustForm').onsubmit=async e=>{e.preventDefault();try{await remoteCall('turf_stock',{p_product:adjustProduct,p_amount:adjustAmount*adjustDirection});await syncRemote(true);$('#adjustDialog').close();showToast(`${adjustAmount} ${PRODUCTS[adjustProduct].name.toLowerCase()} ${adjustDirection===1?'toegevoegd':'afgehaald'}`)}catch(err){showToast('Voorraad aanpassen mislukt')}};
$$('[data-credit]').forEach(b=>b.onclick=()=>{$('#creditAmount').value=Number(b.dataset.credit).toFixed(2)});$('#creditForm').onsubmit=async e=>{e.preventDefault();if(!isAdmin())return;const cents=Math.round(Number($('#creditAmount').value)*100);if(cents>0)try{await remoteCall('turf_admin_credit',{p_admin:state.user,p_pin:adminToken,p_person:creditPerson,p_cents:cents,p_note:'Krediet'});await syncRemote(true);$('#creditDialog').close();showToast(`${money(cents)} toegevoegd voor ${creditPerson}`)}catch(err){showToast('Krediet toevoegen mislukt')}};
$('#newPeriodButton').onclick=async()=>{if(!isAdmin())return;if(!confirm('Nieuwe afrekenperiode starten? Alle huidige tellers en kredieten beginnen weer op nul.'))return;try{await remoteCall('turf_admin_new_period',{p_admin:state.user,p_pin:adminToken});await syncRemote(true);showToast('Nieuwe afrekenperiode gestart')}catch(e){showToast('Nieuwe periode starten mislukt')}};
$('#createReportButton').onclick=createReport;$('#downloadReport').onclick=downloadReport;$('#copyReport').onclick=copyReport;
$('#pinForm').onsubmit=async e=>{e.preventDefault();const pin=$('#pinInput').value,confirmPin=$('#pinConfirm').value;if(!/^\d{4}$/.test(pin)){$('#pinError').textContent='Gebruik precies vier cijfers.';return}if(pinSetup&&pin!==confirmPin){$('#pinError').textContent='De twee PIN-codes zijn niet hetzelfde.';return}try{if(pinSetup){const setupOk=await remoteCall('turf_setup_admin_pin',{p_name:pendingAdmin,p_pin:pin});if(!setupOk){$('#pinError').textContent='PIN kon niet worden ingesteld. Vernieuw de app.';return}}const token=await remoteCall('turf_admin_login',{p_name:pendingAdmin,p_pin:pin});if(!token){$('#pinError').textContent='Deze PIN klopt niet.';$('#pinInput').value='';return}adminToken=token;savedAdminName=pendingAdmin;localStorage.setItem(ADMIN_TOKEN_KEY,token);localStorage.setItem(ADMIN_NAME_KEY,pendingAdmin);state.adminPins[pendingAdmin]=true;$('#pinDialog').close();chooseProfile(pendingAdmin);showToast(pinSetup?'Beheer-PIN veilig ingesteld':'Je blijft 30 dagen ingelogd')}catch(err){$('#pinError').textContent='Geen verbinding met de centrale database.'}};
$$('.nav-item').forEach(b=>b.onclick=()=>{$$('.nav-item').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.view').forEach(v=>v.classList.remove('active'));$('#'+b.dataset.view).classList.add('active');scrollTo({top:0,behavior:'smooth'})});
$('#viewAllButton').onclick=()=>{$$('[data-view="adminView"]')[0].click()};
$('#houseCodeForm').onsubmit=async e=>{e.preventDefault();houseCode=$('#houseCodeInput').value.trim();const ok=await syncRemote(true);if(!ok){houseCode='';$('#houseCodeError').textContent='Deze huiscode klopt niet.';return}localStorage.setItem(HOUSE_CODE_KEY,houseCode);$('#houseCodeDialog').close();if(!state.user)setTimeout(()=>$('#profileDialog').showModal(),200)};
save();render();if(houseCode){syncRemote().then(ok=>{if(ok&&!state.user)setTimeout(()=>$('#profileDialog').showModal(),350);if(!ok){localStorage.removeItem(HOUSE_CODE_KEY);houseCode='';$('#houseCodeDialog').showModal()}})}else setTimeout(()=>$('#houseCodeDialog').showModal(),250);setInterval(()=>{if(houseCode)syncRemote(true)},15000);
